[versions]
agpVersion = "8.12.3"
appcompatVersion = "1.7.1"
assertjCoreVersion = "3.27.4"
constraintlayoutVersion = "2.2.1"
coreKtxVersion = "1.17.0"
desugar_jdk_libsVersion = "2.1.5"
espressoCoreVersion = "3.7.0"
firebaseBomVersion = "34.1.0"
junit = "1.3.0"
junitVersion = "4.13.2"
koinAndroidVersion = "3.5.6"
mockitoCoreVersion = "5.19.0"
mockitoKotlinVersion = "2.2.0"
playServicesOssLicensesVersion = "17.2.2"
recyclerviewVersion = "1.4.0"
swiperefreshlayoutVersion = "1.1.0"

[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertjCoreVersion" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayoutVersion" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libsVersion" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "junit" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBomVersion" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
junit = { module = "junit:junit", version.ref = "junitVersion" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinAndroidVersion" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCoreVersion" }
mockito-kotlin = { module = "com.nhaarman.mockitokotlin2:mockito-kotlin", version.ref = "mockitoKotlinVersion" }
play-services-oss-licenses = { module = "com.google.android.gms:play-services-oss-licenses", version.ref = "playServicesOssLicensesVersion" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerviewVersion" }
swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayoutVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agpVersion" }
android-library = { id = "com.android.library", version.ref = "agpVersion" }


[bundles]
firebase = ['firebase-analytics', 'firebase-crashlytics']