[versions]
activityComposeVersion = "1.11.0"
agpVersion = "8.13.1"
annotationVersion = "1.9.1"
appcompatVersion = "1.7.1"
arrowVersion = "1.2.4"
assertjCoreVersion = "3.27.6"
composeBomVersion = "2025.11.00"
constraintlayoutVersion = "2.2.1"
coreKtxVersion = "1.17.0"
coroutinesVersion = "1.5.1"
desugar_jdk_libsVersion = "2.1.5"
espressoCoreVersion = "3.7.0"
firebaseBomVersion = "34.3.0"
hiltVersion = "2.57.2"
hiltWorkVersion = "1.3.0"
junit = "1.3.0"
junitVersion = "4.13.2"
koinAndroidVersion = "3.5.6"
kotlinVersion = "2.2.10"
lifecycleVersion = "2.9.4"
materialVersion = "1.13.0"
mockitoCoreVersion = "5.20.0"
mockitoKotlinVersion = "2.2.0"
moshiVersion = "1.15.2"
okhttpVersion = "4.9.0"
playServicesOssLicensesVersion = "17.3.0"
preferenceVersion = "1.2.1"
recyclerviewVersion = "1.4.0"
retrofitVersion = "2.9.0"
roomVersion = "2.7.2"
swiperefreshlayoutVersion = "1.1.0"
workVersion = "2.11.0"
worldCountryDataVersion = "1.5.3"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityComposeVersion" }
adaptive = { module = "androidx.compose.material3.adaptive:adaptive" }
annotation = { module = "androidx.annotation:annotation", version.ref = "annotationVersion" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
arrow-core = { module = "io.arrow-kt:arrow-core" }
arrow-optics = { module = "io.arrow-kt:arrow-optics" }
arrow-optics-plugin = { module = "io.arrow-kt:arrow-optics-ksp-plugin", version.ref = "arrowVersion" }
arrow-stack = { module = "io.arrow-kt:arrow-stack", version.ref = "arrowVersion" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertjCoreVersion" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBomVersion" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayoutVersion" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutinesVersion" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutinesVersion" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libsVersion" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "junit" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBomVersion" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
junit = { module = "junit:junit", version.ref = "junitVersion" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltVersion" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltVersion" }
hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hiltWorkVersion" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinAndroidVersion" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.2.1" }
lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycleVersion" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleVersion" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleVersion" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleVersion" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleVersion" }
lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "lifecycleVersion" }
material = { module = "com.google.android.material:material", version.ref = "materialVersion" }
material3 = { module = "androidx.compose.material3:material3" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCoreVersion" }
mockito-kotlin = { module = "com.nhaarman.mockitokotlin2:mockito-kotlin", version.ref = "mockitoKotlinVersion" }
moshi = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshiVersion" }
moshi-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshiVersion" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttpVersion" }
okhttp-logger = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttpVersion" }
play-services-oss-licenses = { module = "com.google.android.gms:play-services-oss-licenses", version.ref = "playServicesOssLicensesVersion" }
preference = { module = "androidx.preference:preference", version.ref = "preferenceVersion" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerviewVersion" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofitVersion" }
retrofit-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofitVersion" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomVersion" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomVersion" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomVersion" }
runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata" }
swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayoutVersion" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
work = { module = "androidx.work:work-runtime-ktx", version.ref = "workVersion" }
work-testing = { module = "androidx.work:work-testing", version.ref = "workVersion" }
worldCountryData = { module = "com.github.blongho:worldCountryData", version.ref = "worldCountryDataVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agpVersion" }
android-library = { id = "com.android.library", version.ref = "agpVersion" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlinVersion" }
google-ksp = { id = "com.google.devtools.ksp", version = "2.2.10-2.0.2" }
google-firebase-crashlytics = { id = "com.google.firebase.crashlytics", version = "3.0.6" }
google-licenses = { id = "com.google.android.gms.oss-licenses-plugin", version = "0.10.9" }
google-services = { id = "com.google.gms.google-services", version = "4.4.4" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hiltVersion" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinVersion" }
versions = { id = "com.github.ben-manes.versions", version = "0.53.0" }


[bundles]
firebase = ['firebase-analytics', 'firebase-crashlytics']
okhttp = ['okhttp', 'okhttp-logger']
retrofit = ['retrofit', 'retrofit-moshi']
room = ['room-runtime', 'room-ktx']
arrow = ['arrow-core', 'arrow-optics']
