name: Run tests

on:
  push:
    branches:
      - '!rel/**'
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Generate keystore.properties
      run: touch keystore.properties
    - name: Write keystore data
      run: |
        echo "storeFile=$storeFile" >> keystore.properties
        echo "storePassword=$storePass" >> keystore.properties
        echo "keyAlias=$keyAlias" >> keystore.properties
        echo "keyPassword=$keyPassword" >> keystore.properties
      env:
        storeFile: ${{ secrets.STOREFILE }}
        storePass: ${{ secrets.STOREPASSWORD }}
        keyAlias: ${{ secrets.KEYALIAS }}
        keyPassword: ${{ secrets.KEYPASSWORD }}
    - name: Generate google-services.json
      run: |
        echo "$GS" | base64 -d >> app/src/google-services.json
      env:
        GS: ${{ secrets.GOOGLE_SERVICES }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run tests
      run: ./gradlew testDebugUnitTest
